### ISSUE TITLE
Holding Space at beginning of game returns error

### ISSUE THREAD

**Issue by Kevin-Mok** [JonPizza/crappybird-py#1]
### Steps to Reproduce the Issue
1. Launch game.
2. Hold Space to reach top of screen.

### What's the expected result?
Return score of 0.

### What's the actual result?
```
Traceback (most recent call last):
  File "main.py", line 121, in <module>
    points = wrapper(main)
  File "/usr/lib/python3.7/curses/__init__.py", line 102, in wrapper
    return func(stdscr, *args, **kwds)
  File "main.py", line 85, in main
    karl.draw(stdscr)
  File "main.py", line 23, in draw
    stdscr.addstr(self.y, 20, '>', curses.color_pair(2))
_curses.error: addwstr() returned ERR
```

**Comment by JonPizza** [comment]
Thanks! Patched
